name: nerf-navigation
channels:
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=11.7
  - python=3.8
  - ninja
  - trimesh
  - opencv
  - tensorboardX
  - numpy 
  - pandas
  - tqdm
  - matplotlib
  - rich
  - packaging
  - scipy
  - torchquad
